[build]
builder = "nixpacks"

[deploy]
start = "dotnet ./build/API.FurnitoreStore.API.dll"

[phases.setup]
nixPkgs = ["dotnet-sdk_8", "dotnet-runtime_8"]

[phases.build]
cmds = [
  "dotnet restore",
  "dotnet publish API.FurnitoreStore.API/API.FurnitoreStore.API.csproj -c Release -o build"
]

[start]
cmd = "dotnet ./build/API.FurnitoreStore.API.dll"
